#!/usr/bin/php
<?php

/*
 * GET:
 *   ZONE_API_TOKEN=user:token ./zone_api_cli
 *   ZONE_API_TOKEN=user:token ./zone_api_cli domain
 *   ZONE_API_TOKEN=user:token ./zone_api_cli domain id
 *
 * SET:
 *   ZONE_API_TOKEN=user:token ./zone_api_cli domain id prefix content
 */

if ( PHP_SAPI != 'cli' )
	exit( 1 );

$token = getenv( 'ZONE_API_TOKEN' );

if ( ! empty( $token ) )
	define( 'ZONE_API_TOKEN', $token );
else
	exit( 1 );

require 'zone_api.php';

if ( ! empty( $argv[ 1 ] ) )
	$domain = $argv[ 1 ];
else
	$domain = '';

if ( ! empty( $argv[ 2 ] ) )
	$id = $argv[ 2 ];
else
	$id = '';

if ( ! empty( $argv[ 3 ] ) and ! empty( $argv[ 4 ] ) )
{
	$r = zone_api_update_record( $domain, $id, $argv[ 3 ], $argv[ 4 ] );

	foreach ( $r->messages as $m )
		printf( "%s\n", $m );

	if ( $r->status != 200 )
		exit( 1 );
}

else
{
	$r = zone_api_get_records( $domain, $id );

	if ( $r->status != 200 )
		exit( 1 );

	foreach ( $r->params as $domain => $zone )
		if ( isset( $zone->A ) )
			foreach ( $zone->A as $a )
				printf( "%s %s %s\n", $a->id, $a->host, $a->content );
}
